# Generated by Django 3.2.7 on 2021-09-14 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7e5098f8-45d6-4f24-a5cb-63e7960924cd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7e5098f8-45d6-4f24-a5cb-63e7960924cd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7e5098f8-45d6-4f24-a5cb-63e7960924cd'), primary_key=True, serialize=False),
        ),
    ]
